namespace DAI.FrostbiteAssets.Enums
{
	public enum CinebotReactionInput
	{
		CINEBOT_REACTION_INPUT_CAMERASLIP,
		CINEBOT_REACTION_INPUT_SPEED,
		CINEBOT_REACTION_INPUT_ACCEL,
		CINEBOT_REACTION_INPUT_VERT_ACCEL,
		CINEBOT_REACTION_INPUT_JERK,
		CINEBOT_REACTION_INPUT_SLOPE,
		CINEBOT_REACTION_INPUT_ROLL,
		CINEBOT_REACTION_INPUT_CAR_SLIP,
		CINEBOT_REACTION_INPUT_CONTROLLER,
		CINEBOT_REACTION_INPUT_RPM,
		CINEBOT_REACTION_INPUT_WORLD_COLLISION,
		CINEBOT_REACTION_INPUT_CAR_COLLISION,
		CINEBOT_REACTION_INPUT_BULLET_IMPACT,
		CINEBOT_REACTION_INPUT_BLACKBOARD,
		CINEBOT_REACTION_INPUT_BLACKBOARD_VEHICLE,
		CINEBOT_REACTION_INPUT_CONTROLLER_RAW,
		CINEBOT_REACTION_INPUT_NUM
	}
}
