namespace DAI.FrostbiteAssets.Enums
{
	public enum CinebotBlendType
	{
		CINEBOT_BLEND_LINEAR,
		CINEBOT_BLEND_EULER,
		CINEBOT_BLEND_CUBIC,
		CINEBOT_BLEND_CATMULROM,
		CINEBOT_BLEND_LINEAR_ORBIT,
		CINEBOT_BLEND_EULER_ORBIT,
		CINEBOT_BLEND_CUBIC_ORBIT,
		CINEBOT_BLEND_CATMULROM_ORBIT
	}
}
