//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAI.AssetLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAI.AssetLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0B87DF4B,Out
        ///00597302,In
        ///AA8E5552,OnTrue
        ///FB1E95D9,OnFalse
        ///0CED1026,OnSet
        ///0B87D373,In1
        ///0B87D372,In0
        ///0002B5E4,A
        ///0002B5E7,B
        ///94770229,Amount
        ///51273EC7,PartyMemberID1
        ///51273EC4,PartyMemberID2
        ///51273EC5,PartyMemberID3
        ///51273EC2,PartyMemberID4
        ///6438DE1B,BaseValue
        ///0B873D1A,A&lt;B
        ///0B873DD8,A&gt;B
        ///9E16DB11,InputList
        ///20D14A5A,Execute
        ///0CECBC32,OnGet
        ///7C7F6A47,A&lt;=B
        ///7764F913,OnActionComplete
        ///29E12EDD,OnTimelineRemoved
        ///0056C23D,IntValue
        ///78369F0E,GenderOverride
        ///333AB864,RaceOverride
        ///2B988771,OutputValue
        ///0A7E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FieldNames {
            get {
                return ResourceManager.GetString("FieldNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54CFA269FAEE88469DEDA794CBC5034F,INT,dai_cur_gold
        ///AB1E9A19EA756F4F9CC7A77080C003A3,INT,dai_cur_fade_shards
        ///555A343CABC0EA449ECAD575E8320333,INT,dai_fade_shards
        ///EAFA732B083891479EB603D71D5F0340,INT,dai_rifts_closed
        ///6FF40F6B0EEE4F4AAF177DB94F020348,INT,dai_dragons_killed
        ///E70F2FB25CC758499C8E6A9CB8D603AB,INT,dai_regions_disc_crestwood
        ///A900FD5C2E50554C892C2DAE683603DF,INT,dai_regions_disc_daleshighlands
        ///AC7908248543DD4B9C411D5243A90392,INT,dai_regions_disc_dalesplains
        ///E322A212CF5FDB41B2CDC0B4B3FB0364,IN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlotFlags {
            get {
                return ResourceManager.GetString("PlotFlags", resourceCulture);
            }
        }
    }
}
