namespace DAI.FrostbiteAssets.Enums
{
	public enum AnyPartyProxyInteractionPolicy
	{
		AnyPartyProxyInteractionPolicy_AnyProxyLooksForTheNextPartyMember,
		AnyPartyProxyInteractionPolicy_UseSharingPolicy,
		AnyPartyProxyInteractionPolicy_SpecificProxyUsed_AnyProxyDisabledExceptTranform,
		AnyPartyProxyInteractionPolicy_SpecificProxyUsed_AnyProxyDisabled
	}
}
