namespace DAI.FrostbiteAssets.Enums
{
	public enum CinebotNoiseParameter
	{
		CINEBOT_NOISE_PARAM_POSITION,
		CINEBOT_NOISE_PARAM_TARGET,
		CINEBOT_NOISE_PARAM_ROLL,
		CINEBOT_NOISE_PARAM_FOV,
		CINEBOT_NOISE_PARAM_HUD_SHAKE
	}
}
