namespace DAI.FrostbiteAssets.Enums
{
	public enum TimeDeltaType
	{
		TIMEDELTA_DILATION_NONE,
		TIMEDELTA_DILATION_PLAYER,
		TIMEDELTA_DILATION_WORLD,
		TIMEDELTA_DILATION_EXTRA1,
		TIMEDELTA_DILATION_EXTRA2,
		TIMEDELTA_DILATION_EXTRA3,
		TIMEDELTA_DILATION_EXTRA4,
		TIMEDELTA_DILATION_EXTRA5,
		TIMEDELTA_COUNT
	}
}
